services:
  - type: web
    name: mbeka-facturation
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
      libcairo2 \
      libpango-1.0-0 \
      libpangocairo-1.0-0 \
      libgdk-pixbuf2.0-0 \
      libffi-dev \
      shared-mime-info
    startCommand: gunicorn app:app
